### ISSUE TITLE
Unittesting does not work

### ISSUE THREAD

**Issue by hoppfrosch** [tariqporter/Gdip2#4]
Did as you described in https://github.com/tariqporter/ahk-unit and https://github.com/tariqporter/Gdip2 to setup the UnitTest-Environment.

Running 
`npm test`
results in following error:
```
> gdip2@2.1.2 test d:\Projects\AHK\_MyWorks\Gdip_2\Gdip2
> ahk-unit ./tests/tests.ahk

fs.js:682
  var r = binding.read(fd, buffer, offset, length, position);
                  ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:682:19)
    at tryReadSync (fs.js:480:20)
    at Object.fs.readFileSync (fs.js:517:19)
    at getDependencies (d:\Projects\AHK\_MyWorks\Gdip_2\Gdip2\node_modules\ahk-unit\lib\cli.js:20:18)
    at getDependencies (d:\Projects\AHK\_MyWorks\Gdip_2\Gdip2\node_modules\ahk-unit\lib\cli.js:32:29)
    at getDependencies (d:\Projects\AHK\_MyWorks\Gdip_2\Gdip2\node_modules\ahk-unit\lib\cli.js:32:29)
    at Object.exports.run (d:\Projects\AHK\_MyWorks\Gdip_2\Gdip2\node_modules\ahk-unit\lib\cli.js:44:21)
    at Object.<anonymous> (d:\Projects\AHK\_MyWorks\Gdip_2\Gdip2\node_modules\ahk-unit\bin\ahk-unit:3:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
npm ERR! Test failed.  See above for more details.
```

**Comment by tariqporter** [comment]
Are you sure you have the latest code? And I assume you're on windows.
I just created a new folder `C:\Users\tic\git\Gdip2`, then:
```bash
cd C:\Users\tic\git\Gdip2
git init
git pull https://github.com/tariqporter/Gdip2.git
npm install
npm test
```

Which results in 
```
Gdip.Point - All tests passed
Gdip.Size - All tests passed
```

**Comment by hoppfrosch** [comment]
You are right - running on a clean new git clone works correctly.

What I did: 
- took my current working project Gdip2 (forked from your repository a couploe of days ago)
- switched to branch `master`
-  synced this with your Gdip2 repository (`git fetch upstream` and  `git merge upstream/master`) 
- `npm install`
- `npm test`

and got the rror message above ...

**Comment by hoppfrosch** [comment]
Closed issue, as my way to reproduce the error is not likely to occur with other users - as they will clone the latest version
